version: "3.9"
services:
  core:
    depends_on:
      - postgres_db
    build:
      context: ./core
      dockerfile: Dockerfile
    image: portfolio:v1
    environment:
      - PORT=8020
    env_file:
      - core/.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    # volumes:
    #    - staticfiles:/app/staticfiles/


  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - core/.env
    expose:
      - 5434
    ports: # For Local systems
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


      


volumes:
  staticfiles:
      external: true
  postgres_data: