name: Build Docker Container and Push to registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test_django_job:
    uses: SeanP94/SeansPortfolio/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLUSTER_NAME: django-portfolio
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login To DO Container Registry with creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: ./core
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/krayte/portfolio-core:latest \
            -t registry.digitalocean.com/krayte/portfolio-core:${GITHUB_SHA::7} \
            .
      - name: Push Image
        run: |
          docker push registry.digitalocean.com/krayte/portfolio-core --all-tags
      - name: k8s cluster kubeconfig file with creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update Secrets
        run: |
          cat << EOF >> core/.env.prod
          DEBUG=${{ secrets.DEBUG }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DB_USE_SSL=${{ secrets.DB_USE_SSL }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_READY=${{ secrets.POSTGRES_READY }}
          PROD = ${{ secrets.PROD }}

          EOF

          kubectl delete secret django-core-env
          kubectl create secret generic django-core-env --from-env-file=core/.env.prod

      - name: Update Deployment image
        run: |
          kubectl set image deployment/django-core-deployment portfolio-core=registry.digitalocean.com/krayte/portfolio-core:${GITHUB_SHA::7}
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/django-core-deployment
      - name: Migrate DB
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=django-core-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh